AllCops:
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 200

Style/NumericLiterals:
  MinDigits: 6

Style/FrozenStringLiteralComment:
  Enabled: false